// an array of objects that contain information about recipes

const recipes = [
  {
    title: "Spicy Thai Basil Chicken Stir-Fry",
    imageSrc: "https://j6e2i8c9.rocketcdn.me/wp-content/uploads/2020/07/Thai-basil-chicken-33.jpg",
    description: "This vibrant stir-fry combines tender chicken, colorful vegetables, Thai basil, and spicy chili sauce for a flavorful and aromatic Thai-inspired dish. Serve over jasmine rice.",
    ingredients: [
      "2 boneless, skinless chicken breasts, sliced",
      "1 tablespoon vegetable oil",
      "2 cloves garlic, minced",
      "1 red bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 onion, sliced",
      "1 cup fresh Thai basil leaves",
      "2 tablespoons soy sauce",
      "1 tablespoon oyster sauce",
      "1 tablespoon fish sauce",
      "1 teaspoon sugar",
      "1/2 teaspoon red pepper flakes",
      "Cooked jasmine rice, for serving",
    ],
  },
  {
    title: "Creamy Garlic Parmesan Pasta",
    imageSrc: "https://midwestfoodieblog.com/wp-content/uploads/2019/03/FINAL-Parmesan-garlic-pasta-1-3.jpg",
    description: "Enjoy a comforting bowl of creamy garlic Parmesan pasta with al dente spaghetti coated in a rich sauce made with garlic, butter, cream, and Parmesan cheese. Top with parsley and extra Parmesan.",
    ingredients: [
      "8 oz spaghetti",
      "2 tablespoons butter",
      "4 cloves garlic, minced",
      "1 cup heavy cream",
      "1 cup grated Parmesan cheese",
      "Salt and black pepper to taste",
      "Chopped fresh parsley, for garnish"
    ],
  },
  {
    title: "Grilled Citrus Salmon with Mango Salsa",
    imageSrc: "https://thecookingjar.com/wp-content/uploads/2018/05/2013-08-12-14.58.362-e1398056489112.jpg",
    description: "Elevate your seafood experience with grilled citrus salmon marinated in a zesty glaze. Topped with tropical mango salsa, this dish offers a burst of citrus and fruity flavors. Serve with asparagus or quinoa.",
    ingredients: [
      "1 lb salmon fillet",
      "1/4 cup orange juice",
      "1/4 cup lemon juice",
      "1/4 cup lime juice",
      "1/4 cup honey",
      "1 tablespoon soy sauce",
      "1 tablespoon olive oil",
      "1 teaspoon red pepper flakes",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
      "1 mango, diced",
      "1/2 red bell pepper, diced",
      "1/2 red onion, diced",
      "1 jalapeno, diced",
      "1/4 cup chopped fresh cilantro",
      "1 tablespoon lime juice",
    ],
  },
  {
    title: "Classic Margherita Pizza",
    imageSrc:  "https://ohsweetbasil.com/wp-content/uploads/four-cheese-margherita-pizza-recipe-12-scaled.jpg",
    description: "Indulge in the simplicity of a classic Margherita pizza with fresh basil leaves, mozzarella cheese, and tomato sauce on a thin and crispy crust.",
    ingredients: [
      "1 lb pizza dough",
      "1/2 cup tomato sauce",
      "1 cup shredded mozzarella cheese",
      "1/4 cup fresh basil leaves",
      "1 tablespoon olive oil",
      "Salt and black pepper to taste",
    ],
  },
  {
    title: "Lemon Herb Roasted Chicken",
    imageSrc: "https://www.cuisinart.com/globalassets/recipes/recipe_148_492918392.jpg",
    description: "Enjoy tender and juicy roasted chicken infused with the flavors of lemon, garlic, and a medley of herbs. Perfectly seasoned and roasted to golden perfection.",
    ingredients: [
      "1 whole chicken",
      "1 lemon, sliced",
      "1/4 cup butter, softened",
      "4 cloves garlic, minced",
      "1 tablespoon chopped fresh rosemary",
      "1 tablespoon chopped fresh thyme",
      "1 tablespoon chopped fresh parsley",
      "1 teaspoon salt",
      "1/2 teaspoon black pepper",
    ],
  },
  {
    title: "Vegetable Stir-Fry with Tofu",
    imageSrc: "https://www.funfoodfrolic.com/wp-content/uploads/2020/03/Tofu-Stir-Fry-Thumbnail.jpg",
    description: "Savor the goodness of a colorful vegetable stir-fry with tofu, packed with crunchy vegetables and tossed in a savory sauce. Serve over steamed rice or noodles.",
    ingredients: [
      "1 (14 oz) package firm tofu, drained and cubed",
      "1 tablespoon vegetable oil",
      "1 red bell pepper, sliced",
      "1 green bell pepper, sliced",
      "1 cup broccoli florets",
      "1 cup sliced carrots",
      "1 cup sliced mushrooms",
      "1 cup snow peas",
      "1/2 cup sliced green onions",
      "1/2 cup vegetable broth",
      "1/4 cup soy sauce",
    ],
  },
  {
    title: "Mouthwatering BBQ Ribs",
    imageSrc: "https://www.allrecipes.com/thmb/gVocwHi0RMwyjfJ1g6q8VHacxJU=/1500x0/filters:no_upscale():max_bytes(150000):strip_icc()/22469-Barbecue-Ribs-ddmfs-4x3-208-0221b0213517493494a29c1c76a8d1cc.jpg",
    description: "Fall-off-the-bone tender and smoky BBQ ribs that are perfectly glazed with a tangy and sweet sauce. Serve with your favorite sides for a delicious barbecue feast.",
    ingredients: [
      "1 (2 lb) rack baby back ribs",
      "1 cup barbecue sauce",
      "1/4 cup brown sugar",
      "1/4 cup apple cider vinegar",
      "1/4 cup honey",
      "1 tablespoon Worcestershire sauce",
      "1 tablespoon Dijon mustard",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "1 teaspoon paprika",
      "1/2 teaspoon salt",
      "1/2 teaspoon black pepper",
    ],
  },
  {
    title: "Gourmet Beef Burger",
    imageSrc: "https://i.ytimg.com/vi/g9Rpv78PkrE/maxresdefault.jpg",
    description: "Sink your teeth into a juicy and flavorful gourmet beef burger topped with melted cheese, fresh vegetables, and a special sauce. Perfect for your next cookout or weekend treat.",
    ingredients: [
      "1 lb ground beef",
      "4 hamburger buns",
      "4 slices cheddar cheese",
      "4 slices tomato",
      "4 lettuce leaves",
      "1/4 cup mayonnaise",
      "1/4 cup ketchup",
      "1 tablespoon mustard",
      "1 tablespoon Worcestershire sauce",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "1 teaspoon paprika",
      "1/2 teaspoon salt",
      "1/2 teaspoon black pepper",
    ],
  },
  {
    title: "Caprese Salad with Balsamic Glaze",
    imageSrc: "https://cdn.apartmenttherapy.info/image/upload/f_jpg,q_auto:eco,c_fill,g_auto,w_1500,ar_4:3/k%2Farchive%2F3b432b41ce04c96a08d77befa42b9881a587a436",
    description: "Enjoy a refreshing Caprese salad made with ripe tomatoes, fresh mozzarella cheese, and fragrant basil leaves. Drizzle with balsamic glaze for an extra burst of flavor.",
    ingredients: [
      "2 large tomatoes, sliced",
      "8 oz fresh mozzarella cheese, sliced",
      "1/4 cup fresh basil leaves",
      "2 tablespoons olive oil",
    ],
  },
  {
    title: "Chicken Alfredo Lasagna",
    imageSrc: "https://cdn.greatlifepublishing.net/wp-content/uploads/sites/2/2021/12/15134625/Chicken-Alfredo-Lasagna-Vertical-3.jpg",
    description: "Indulge in layers of tender chicken, creamy Alfredo sauce, lasagna noodles, and melted cheese in this decadent and satisfying chicken Alfredo lasagna.",
    ingredients: [
      "1 lb lasagna noodles",
      "2 cups cooked chicken, shredded",
      "1 (15 oz) jar Alfredo sauce",
      "1 (15 oz) container ricotta cheese",
      "1 (10 oz) package frozen chopped spinach, thawed and drained",
      "1 cup shredded mozzarella cheese",
      "1/2 cup grated Parmesan cheese",
      "1/2 cup milk",
      "1 egg",
      "1 teaspoon garlic powder",
    ],
  },
  {
    title: "Crispy Honey-Glazed Salmon",
    imageSrc: "https://www.unicornsinthekitchen.com/wp-content/uploads/2019/08/Orang-Glaze-Salmon-7-500x500.jpg",
    description: "Delight in the irresistible combination of crispy-skinned salmon glazed with a sweet and sticky honey sauce. Served with a side of steamed vegetables or roasted potatoes.",
    ingredients: [
      "4 (6 oz) salmon fillets",
      "1/4 cup honey",
      "1/4 cup soy sauce",
      "1 tablespoon olive oil",
      "1 tablespoon lemon juice",
      "1 teaspoon garlic powder",
      "1 teaspoon onion powder",
      "1/2 teaspoon salt",
      "1/2 teaspoon black pepper",
    ],
  },
  {
    title: "Penne Arrabbiata",
    imageSrc: "https://www.skinnytaste.com/wp-content/uploads/2009/10/Mushroom-Risotto_1-4.jpg",
    description: "Tantalize your taste buds with a spicy and flavorful Penne Arrabbiata, featuring al dente pasta tossed in a fiery tomato sauce infused with garlic, chili flakes, and fresh herbs.",
    ingredients: [
      "1 lb penne pasta",
      "1 (28 oz) can crushed tomatoes",
      "1/4 cup olive oil",
      "1/4 cup fresh basil leaves",
      "1/4 cup fresh parsley leaves",
      "1/4 cup grated Parmesan cheese",
      "2 tablespoons tomato paste",
      "2 tablespoons red pepper flakes",
      "2 tablespoons garlic, minced",
      "1 tablespoon sugar",
    ],
  },
  {
    title: "Mushroom Risotto",
    imageSrc: "https://cdn.loveandlemons.com/wp-content/uploads/2023/01/mushroom-risotto.jpg",
    description: "Indulge in a creamy and rich mushroom risotto made with Arborio rice, sautéed mushrooms, Parmesan cheese, and a touch of white wine. A comforting and elegant dish.",
    ingredients: [
      "1 cup Arborio rice",
      "1 cup mushrooms, sliced",
      "1/4 cup white wine",
      "1/4 cup grated Parmesan cheese",
      "1/4 cup fresh parsley leaves",
      "1/4 cup fresh basil leaves",
      "1/4 cup olive oil",
      "2 tablespoons garlic, minced",
      "1 tablespoon butter",
      "1 teaspoon salt",
      "1 teaspoon black pepper",
    ],
  },
  {
    title: "Baked Spinach and Artichoke Dip",
    imageSrc: "https://therecipecritic.com/wp-content/uploads/2019/12/spinach_artichoke_dip2.jpg",
    description: "Enjoy a creamy and cheesy baked spinach and artichoke dip that's perfect for parties or game nights. Serve with tortilla chips or toasted bread for a delicious appetizer.",
    ingredients: [
      "1 (14 oz) can artichoke hearts, drained and chopped",
      "1 (10 oz) package frozen chopped spinach, thawed and drained",
      "1 cup shredded mozzarella cheese",
      "1/2 cup grated Parmesan cheese",
      "1/2 cup sour cream",
      "1/2 cup mayonnaise",
      "1/4 cup cream cheese",
      "1/4 cup milk",
      "2 tablespoons garlic, minced",
      "1 teaspoon salt",
      "1 teaspoon black pepper",
    ],
  },
  {
    title: "Cajun Shrimp Pasta",
    imageSrc: "https://selfproclaimedfoodie.com/wp-content/uploads/cajun-shrimp-pasta-4.jpg",
    description: "Savor the bold and spicy flavors of Cajun shrimp pasta, featuring succulent shrimp cooked in a creamy sauce with Cajun seasoning, bell peppers, and onions. Serve over linguine or fettuccine.",
    ingredients: [
      "1 lb shrimp, peeled and deveined",
      "1 lb linguine",
      "1 cup heavy cream",
      "1/2 cup chicken broth",
      "1/2 cup grated Parmesan cheese",
      "1/4 cup olive oil",
      "1/4 cup fresh parsley leaves",
      "1/4 cup fresh basil leaves",
      "2 tablespoons garlic, minced",
      "1 tablespoon Cajun seasoning",
      "1 tablespoon lemon juice",
      "1 teaspoon salt",
      "1 teaspoon black pepper",
    ],
  },
];

export default recipes